*******************************************************************************
****** sense_amp schematic my_lib  <vs>  sense_amp layout my_lib
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(inv1_1x schematic my_lib, _) Cell                1       0*
(g45n1svt) MOS                                    3       4*
(g45p1svt) MOS                                    2       3*
                                             ------  ------
Total                                             6       7

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    4       4           4       4
(g45p1svt) MOS                                    3       3           3       3
                                             ------  ------      ------  ------
Total                                             7       7           7       7

Schematic and Layout Match
