*******************************************************************************
****** mux4x1 schematic my_lib  <vs>  mux4x1 layout my_lib
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    4       4
(g45n1svt) MOS                                    4       4
                                             ------  ------
Total                                             8       8

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    4       4           2       2
(g45p1svt) MOS                                    4       4           2       2
(g45n1svt:SerMos2#1) MosBlk                       -       -           1       1
(g45p1svt:SerMos2#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                             8       8           6       6

Schematic and Layout Match
