*******************************************************************************
****** nand3 schematic my_lib  <vs>  nand3 layout my_lib
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    3       3
(g45n1svt) MOS                                    3       3
                                             ------  ------
Total                                             6       6

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45n1svt) MOS                                    3       3           0       0
(g45p1svt) MOS                                    3       3           0       0
(g45n1svt:SerMos3#1) MosBlk                       -       -           1       1
(g45p1svt:ParMos3#1) MosBlk                       -       -           1       1
                                             ------  ------      ------  ------
Total                                             6       6           2       2

Schematic and Layout Match
