*******************************************************************************
****** precharge schematic my_lib  <vs>  precharge layout my_lib
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(g45p1svt) MOS                                    2       2
                                             ------  ------
Total                                             2       2

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(g45p1svt) MOS                                    2       2           2       2
                                             ------  ------      ------  ------
Total                                             2       2           2       2

Schematic and Layout Match
